# Generated by Django 5.0.2 on 2024-03-08 02:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default='12:00')),
                ('end_time', models.TimeField(default='20:00')),
            ],
        ),
        migrations.CreateModel(
            name='InquirySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=70)),
                ('instagram', models.CharField(max_length=80)),
                ('design_type', models.CharField(choices=[('CU', 'Custom'), ('FL', 'Flash'), ('FR', 'Freehand')], default='CU', max_length=2)),
                ('description', models.TextField(max_length=180)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inquirysubmission')),
            ],
        ),
    ]
