# Generated by Django 5.0.2 on 2024-03-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirysubmission',
            name='design_type',
            field=models.CharField(choices=[('Custom', 'Custom'), ('Flash', 'Flash'), ('Freehand', 'Freehand')], default='Custom', max_length=8),
        ),
    ]
